name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.RELEASE_USERNAME }}/lunchy-web:v0.0.0
    - name: Login to the Docker repository
      run: docker login --username ${{ secrets.RELEASE_USERNAME }} --password ${{ secrets.RELEASE_KEY }}
    - name: Push the docker image to GitHub registry
      run: docker push ${{ secrets.RELEASE_USERNAME }}/lunchy-web:v0.0.0
